name: Github Webhook Action
description: Post action results to api endpoint
author: YeouidoPartners

inputs:
  message:
    description: "Message to send"
    required: true

runs:
  using: node16
  main: dist/index.js

branding:
  icon: "activity"
  color: "green"
